events {}

http {
    resolver 127.0.0.11 valid=10s;

    map $http_x_nginx_hops $can_forward {
        ""      1;
        "1"     1;
        default 0;
    }

    map $http_x_nginx_hops $next_hops {
        ""      "1";
        "1"     "2";
        default "3";
    }

    split_clients "$request_id" $random_choice {
        33.33%  "to_python";
        33.33%  "to_nginx1";
        *       "to_nginx2";
    }

    map "${can_forward}:${random_choice}" $upstream_host {
        "1:to_nginx1"   "nginx1";
        "1:to_nginx2"   "nginx2";
        default         "python_app";
    }

    server {
        listen 80;

        location / {
            proxy_pass         http://$upstream_host;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header   X-Nginx-Hops     $next_hops;
            proxy_set_header   Host             $host;
        }
    }
}
